### PR TITLE
Fixed type definitions for typescript and extended the examples to include a typescript project

### PR DESCRIPTION
**Pull request by rodrigoelp**
As indicated in the issue #271, the typescript definition file does not produce a valid output when trying to compile the code and execute it.

The root cause of this issue is the way the class is exported via `export default` in the module, creating an access to the namespace as opposed to the prototype as such. This generates an `invariant violation: element type is invalid`

Based on how this library is written, creating a type definition with a default export as indicated generates the following code when compiled
``` javascript
render() {
     return (React.createElement(react_native_1.View, { style: { flex: 1, backgroundColor: "black" } },
         React.createElement(lottie_react_native_1.default, { source: require("./animation.json"), progress: this.state.animatedProgress })));
}
```

Instead of:
``` javascript
render() {
     return (React.createElement(react_native_1.View, { style: { flex: 1, backgroundColor: "black" } },
         React.createElement(lottie_react_native_1, { source: require("./animation.json"), progress: this.state.animatedProgress })));
}
```
The difference being: `.default` after `lottie_react_native_1`

In order to fix this issue, the type definition was rewritten and an example was created to illustrate the appropriate use of the library for typescript.
To avoid misunderstanding, the example folder was replaced with an `examples` folder containing the previous javascript example and a new folder containing an almost identical copy written for typescript can be found in the `typescript` folder.

### CODE REVIEW

**Comment by rodrigoelp** [comment]
Optionally, I could create a pull request that just contains the typescript definition update and the example can be done as part of the readme file

**Comment by dannycochran** [comment]
LGTM as author of the file originally. It might make the review go faster to just update the TS definition file, though.

Pinging @gpeal -- it'd be good to get this merged and released, it blocks easy usage of lottie-rn with TypeScript.

**Comment by rodrigoelp** [comment]
Is there any update on this?

**Comment by gpeal** [comment]
@rodrigoelp I don't feel comfortable duplicating the example project because it'll just become two project that have to be updated for any change. I would be okay if the sample project itself was ts though so we could just convert it in place rather than duplicate it.

**Comment by rodrigoelp** [comment]
Hi @gpeal, understood. Should I change the pull request? Has LGTM review the type definition? in that case I would be happy to do the changes and revert back to a single example

**Comment by gpeal** [comment]
@rodrigoelp I'm happy to stamp the type definition changes on their own and you can do the sample as a separate PR.

**Comment by rodrigoelp** [comment]
Ok @gpeal, I will update the pull request to just have the type definition 👍

**Comment by rodrigoelp** [comment]
Closing this pull request as I have created a new one here #291

**Pull request closed without merging**
