### PR TITLE
Fix build failures caused by RN0.4

### PR DESCRIPTION
**Pull request by offwhite**

### CODE REVIEW

**Comment by zawarudo** [comment]
I was trying this myself to plow through the issues but is it really advisable to remove the import check statements?

**Comment by lelandrichardson** [comment]
@offwhite this doesn't look correct. If this is causing issues for you, we need to solve it a different way. Perhaps the order needs to change?

**Comment by zawarudo** [comment]
@lelandrichardson This is also what I had to do to bypass issue #32 but it gave me new issues about not being able to import lottie.h

**Comment by lelandrichardson** [comment]
@zawarudo hang tight. We are working on a solution to this. Fix is incoming, but will take place in lottie-ios

**Pull request closed without merging**
