### PR TITLE
[Android] Add imageAssetsFolder prop

### PR DESCRIPTION
**Pull request by fdnhkj**
This PR adds support for imageAssetsFolder prop - see [airbnb/lottie-android#image-support](https://github.com/airbnb/lottie-android#image-support).

**Example**
```
<Animation
  style={{
    width: 200,
    height: 200,
  }}
  source={require('./data.json')}
  progress={this.state.progress}
  imageAssetsFolder={'lottie/images'}
/>
```
capture d ecran 2017-03-30 a 00 46 45

**Tasks**
- [x] Add imageAssetsFolder prop
- [x] Update docs

### CODE REVIEW

**Comment by jerolimov** [comment]
That works fine, but a way to use the relativ images to the json file would be nice.

Have you also a solution to use images file under iOS?

**Comment by fdnhkj** [comment]
@jerolimov I followed instructions regarding image support in [lottie-android](https://github.com/airbnb/lottie-android) & [lottie-ios](https://github.com/airbnb/lottie-ios) projects.

**Comment by arush** [comment]
@fdnhkj in ios, using lottie-react-native, my jsons are referencing images relative to the json file, but it doesn't seem to work. can you explain what you meant by this? Do you have an example bodymovin export that references images and works in lottie-react-native? 
Thanks

> For iOS support, no code change is needed in lottie-react-native.

**Comment by fdnhkj** [comment]
@arush I did it few weeks ago but from what I remember I added the images in the ios project and referenced them in the target in Xcode as explained in lottie-ios README

> To bundle JSON just add it and any images that the animation requires to your target in xcode.

**Comment by twitwi** [comment]
+1
I have animations with images that were failing to play and that I can now play if I apply this PR.

**Comment by theplatapi** [comment]
Is this going to be merged in the near future? Really need this feature.

**Comment by gpeal** [comment]
@fdnhkj is this still WIP?

**Comment by fdnhkj** [comment]
I lost a bit focus on this one as I didn't need image support anymore.
For those interested, this is why:
- [bodymovin/bodymovin/wiki/Shapes#illustrator-layers](https://github.com/bodymovin/bodymovin/wiki/Shapes#illustrator-layers)
-  https://twitter.com/fdnhkj/status/847532085216772096)

@gpeal I just updated docs for this change. To me, this PR can already be merged :) Only improvement I see is updating the example to demo this feature but I have limited resources these days to do it.

**Pull request merged**
