### PR TITLE
Handling Android RN 0.47 breaking change

### PR DESCRIPTION
**Pull request by bahaa96**
[facebook/react-native@ce6fb33](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8)

### CODE REVIEW

**Comment by radko93** [comment]
This was already proposed in #169.

**Comment by bahaa96** [comment]
It wasnt applied yet

**Comment by radko93** [comment]
This one is just a duplicate.

**Comment by gpeal** [comment]
Just merged #169. I'll publish a release soon.

**Pull request closed without merging**
